
name: Release Build

# Controls when the action will run. Triggers the workflow on push of a tag that matches the wildcard
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
    - uses: nuget/setup-nuget@v1

    - name: Get Tag
      shell: powershell
      run: |
        echo "REF $GITHUB_REF"
        echo ".REF $GITHUB.REF"
        $groups = $( Select-String -InputObject "${{GITHUB_REF}}" -Pattern 'v(\d+)\.(\d+)\.(\d+)(.*)' ).Matches.Groups
        echo "RELEASE_VERSION=$($groups[0])" >> $GITHUB_ENV
        echo "Major=$( $groups[1] )"  >> $GITHUB_ENV 
        echo "Minor=$( $groups[2] )"  >> $GITHUB_ENV
        echo "Revision=$( $groups[3] )"  >> $GITHUB_ENV
        echo "SemVerSuffix=$( $groups[4] )"  >> $GITHUB_ENV

    - name: Print Version Info
      shell: powershell
      run:  |
          echo "Major ==> ${env:Major}"
          echo "Minor ==> ${env:Minor}"
