
name: Release Build

# Controls when the action will run. Triggers the workflow on push of a tag that matches the wildcard
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
    - uses: nuget/setup-nuget@v1

    - name: Get Tag
      shell: powershell
      run: |       
        echo "from EnvironmentVariable = ${env:GITHUB_REF}"
        echo "from context = ${{ github.ref }}"
        $groups = $( Select-String -InputObject "${{ github.ref }}" -Pattern 'v(\d+)\.(\d+)\.(\d+)(.*)' ).Matches.Groups       
        
        echo "RELEASE_VERSION=$($groups[0])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "Major=$( $groups[1] )"  | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "Minor=$( $groups[2] )"  | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "Revision=$( $groups[3] )" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append 
        echo "SemVerSuffix=$( $groups[4] )" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append 

    - name: Print Version Info
      shell: powershell
      run:  |
          echo "Major ==> ${env:Major}"
          echo "Minor ==> ${env:Minor}"
